### ISSUE TITLE
Why it all black?

### ISSUE THREAD

**Issue by lucasjinreal** [monokim/PyRacing#1]
It seems all black?

![image](https://user-images.githubusercontent.com/21303438/68474974-cd706580-0261-11ea-9bfa-70c394ee4e4e.png)

**Comment by monokim** [comment]
For the speed of processing, I turned off showing game
You can turn on with env.set_view to True in simulate() Pyrace_RL.py

**Comment by lucasjinreal** [comment]
@monokim  Hi, if I want start 50 cars at the same time to learn, how to set the params?

**Comment by monokim** [comment]
> @monokim Hi, if I want start 50 cars at the same time to learn, how to set the params?

You have to make multiple agents. And I'm not sure OpenAI supports multiple agents and even if they have, I have no idea how to do it.
I guess it will help you out.
https://stackoverflow.com/questions/44369938/openai-gym-environment-for-multi-agent-games

**Comment by AnormalDuck** [comment]
Hi @monokim is it possible to first make the ai learn for a few episodes and then set: env.set_view to true???

**Comment by monokim** [comment]
> Hi @monokim is it possible to first make the ai learn for a few episodes and then set: env.set_view to true???

Yes, you can just set False at the first and after few episodes set True again.
you can switch on/off anytime
